/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getHello'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lấy danh sách tất cả users (chỉ ADMIN) */
    get: operations['UsersController_findAll'];
    put?: never;
    /** Tạo user mới (chỉ ADMIN) */
    post: operations['UsersController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lấy user theo ID (chỉ ADMIN) */
    get: operations['UsersController_findOne'];
    put?: never;
    post?: never;
    /** Xoá user (chỉ ADMIN) */
    delete: operations['UsersController_remove'];
    options?: never;
    head?: never;
    /** Cập nhật user (chỉ ADMIN) */
    patch: operations['UsersController_update'];
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đăng ký tài khoản mới */
    post: operations['AuthController_register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đăng nhập bằng email và mật khẩu */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đổi refresh token lấy token pair mới */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đăng xuất (revoke refresh token) */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lấy danh sách bài viết (công khai) */
    get: operations['PostsController_findAll'];
    put?: never;
    /** Tạo bài viết mới (ADMIN hoặc EDITOR) */
    post: operations['PostsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/posts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lấy bài viết theo ID (công khai) */
    get: operations['PostsController_findOne'];
    put?: never;
    post?: never;
    /** Xoá bài viết (ADMIN: any | EDITOR: own) */
    delete: operations['PostsController_remove'];
    options?: never;
    head?: never;
    /** Cập nhật bài viết (ADMIN: any | EDITOR: own) */
    patch: operations['PostsController_update'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateUserDto: {
      /**
       * @description Tên người dùng
       * @example Nguyen Van A
       */
      name: string;
      /**
       * @description Email (unique)
       * @example nguyenvana@example.com
       */
      email: string;
      /**
       * @description Mật khẩu
       * @example Secret@123
       */
      password: string;
      /**
       * @description Vai trò: admin | editor | viewer
       * @default editor
       * @enum {string}
       */
      role: 'admin' | 'editor' | 'viewer';
    };
    User: {
      /**
       * @description UUID tự sinh
       * @example a1b2c3d4-...
       */
      id: string;
      /** @example Nguyen Van A */
      name: string;
      /** @example nguyenvana@example.com */
      email: string;
      /** @example google-oauth2|1234567890 */
      googleId?: Record<string, never>;
      /** @example apple-sub-1234567890 */
      appleId?: Record<string, never>;
      /**
       * @default editor
       * @enum {string}
       */
      role: 'admin' | 'editor' | 'viewer';
      /** @example true */
      isActive: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateUserDto: {
      /**
       * @description Tên người dùng
       * @example Nguyen Van B
       */
      name?: string;
      /**
       * @description Email mới (unique)
       * @example newmail@example.com
       */
      email?: string;
      /**
       * @description Mật khẩu mới
       * @example NewSecret@456
       */
      password?: string;
      /**
       * @description Vai trò: admin | editor | viewer
       * @enum {string}
       */
      role?: 'admin' | 'editor' | 'viewer';
      /**
       * @description Trạng thái hoạt động
       * @example true
       */
      isActive?: boolean;
    };
    RegisterDto: {
      /** @example Nguyen Van A */
      name: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * @description Tối thiểu 8 ký tự, có chữ hoa, chữ thường và số
       * @example P@ssw0rd!
       */
      password: string;
      /**
       * @description Chỉ cho phép: editor | viewer (admin cần tạo qua /users)
       * @default editor
       * @enum {string}
       */
      role: 'editor' | 'viewer';
    };
    UserProfileDto: {
      id: string;
      name: string;
      email: string;
      /** @enum {string} */
      role: 'admin' | 'editor' | 'viewer';
    };
    AuthResponseDto: {
      /** @description JWT access token, hết hạn sau 15 phút */
      accessToken: string;
      /** @description Refresh token, hết hạn sau 7 ngày */
      refreshToken: string;
      user: components['schemas']['UserProfileDto'];
    };
    LoginDto: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example P@ssw0rd! */
      password: string;
    };
    RefreshTokenDto: {
      /** @description Refresh token nhận được khi đăng nhập */
      refreshToken: string;
    };
    CreatePostDto: {
      /**
       * @description Tiêu đề
       * @example Tiêu đề bài viết hay
       */
      title: string;
      /**
       * @description Nội dung
       * @example Nội dung chi tiết bài viết...
       */
      content: string;
      /**
       * @description Slug SEO (chỉ chứa a-z, 0-9 và dấu gạch ngang)
       * @example tieu-de-bai-viet-hay
       */
      slug?: string;
      /**
       * @description Trạng thái bài viết
       * @default draft
       * @enum {string}
       */
      status: 'draft' | 'published' | 'archived';
    };
    Post: {
      /**
       * @description UUID tự sinh
       * @example a1b2c3d4-...
       */
      id: string;
      /** @example Tiêu đề bài viết */
      title: string;
      /** @example Nội dung bài viết... */
      content: string;
      /** @example tieu-de-bai-viet */
      slug?: Record<string, never>;
      /**
       * @default draft
       * @enum {string}
       */
      status: 'draft' | 'published' | 'archived';
      /** @description ID của tác giả */
      authorId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdatePostDto: {
      /**
       * @description Tiêu đề
       * @example Tiêu đề bài viết hay
       */
      title?: string;
      /**
       * @description Nội dung
       * @example Nội dung chi tiết bài viết...
       */
      content?: string;
      /**
       * @description Slug SEO (chỉ chứa a-z, 0-9 và dấu gạch ngang)
       * @example tieu-de-bai-viet-hay
       */
      slug?: string;
      /**
       * @description Trạng thái bài viết
       * @default draft
       * @enum {string}
       */
      status: 'draft' | 'published' | 'archived';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Danh sách users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'][];
        };
      };
    };
  };
  UsersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
    responses: {
      /** @description User đã được tạo */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  UsersController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Thông tin user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Không tìm thấy user */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Xoá thành công */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Không tìm thấy user */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto'];
      };
    };
    responses: {
      /** @description User sau khi cập nhật */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Không tìm thấy user */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Email đã tồn tại */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Email hoặc mật khẩu không đúng */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Refresh token không hợp lệ hoặc đã hết hạn */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  PostsController_findAll: {
    parameters: {
      query?: {
        /** @description Lọc theo trạng thái */
        status?: 'draft' | 'published' | 'archived';
        /** @description Lọc theo authorId */
        authorId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Danh sách bài viết */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Post'][];
        };
      };
    };
  };
  PostsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePostDto'];
      };
    };
    responses: {
      /** @description Bài viết đã được tạo */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Post'];
        };
      };
    };
  };
  PostsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Chi tiết bài viết */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Post'];
        };
      };
      /** @description Không tìm thấy bài viết */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PostsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Xoá thành công */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Không tìm thấy bài viết */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  PostsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePostDto'];
      };
    };
    responses: {
      /** @description Bài viết sau khi cập nhật */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Post'];
        };
      };
      /** @description Không tìm thấy bài viết */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
